# Generated by Django 4.2.4 on 2023-10-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_profile_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
