# Generated by Django 4.2.4 on 2023-10-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_profile_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
