# Generated by Django 4.2.4 on 2023-10-11 05:50

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_alter_profile_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='font_preference',
            field=models.CharField(default='Font1', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='color',
            field=colorfield.fields.ColorField(default='#0000000', image_field=None, max_length=25, samples=None),
        ),
    ]
