# Generated by Django 4.2.4 on 2023-10-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0014_location_alter_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
