# Generated by Django 4.2.4 on 2023-10-13 13:49

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0018_alter_profile_font_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='color',
            field=colorfield.fields.ColorField(default='#720026', image_field=None, max_length=25, samples=None),
        ),
    ]
