# Generated by Django 4.2.4 on 2023-10-21 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0019_alter_profile_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, unique=True, verbose_name=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            preserve_default=False,
        ),
    ]
