# Generated by Django 4.2.4 on 2023-10-21 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0020_rename_firstname_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
